name: TSCTutorial
author: AlonsoAliaga
version: 1.0
main: com.alonsoaliaga.tscplugin.Main
description: Tsc videos
depend:
- AlonsoJDA
commands:
  verify:
    usage: /verify
    description: Command to verify